/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo.todo;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App app = new App();
        assertNotNull(app.getGreeting(), "app should have a greeting");
    }

    @Test
    void appGetNum() {
        App app = new App();
        assertEquals(app.getNum(), 10);
    }
}
